export const POST_CONTACT_EMAIL_REQUEST = "POST_CONTACT_EMAIL_REQUEST"
export const POST_CONTACT_EMAIL_SUCCESS = "POST_CONTACT_EMAIL_SUCCESS"
export const POST_CONTACT_EMAIL_ERROR = "POST_CONTACT_EMAIL_ERROR"